/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        ink: {
          50: "rgb(var(--ink-50) / <alpha-value>)",
          100: "rgb(var(--ink-100) / <alpha-value>)",
          200: "rgb(var(--ink-200) / <alpha-value>)",
          300: "rgb(var(--ink-300) / <alpha-value>)",
          400: "rgb(var(--ink-400) / <alpha-value>)",
          500: "rgb(var(--ink-500) / <alpha-value>)",
          600: "rgb(var(--ink-600) / <alpha-value>)",
          700: "rgb(var(--ink-700) / <alpha-value>)",
          800: "rgb(var(--ink-800) / <alpha-value>)",
          900: "rgb(var(--ink-900) / <alpha-value>)",
          950: "rgb(var(--ink-950) / <alpha-value>)",
        },
        brand: {
          DEFAULT: "rgb(var(--color-primary) / <alpha-value>)",
          hover: "rgb(var(--color-primary-hover) / <alpha-value>)",
          "on-dark": "rgb(var(--color-primary-on-dark) / <alpha-value>)",
          tint: "rgb(var(--color-primary-tint) / <alpha-value>)",
          50: "rgb(var(--brand-50) / <alpha-value>)",
          100: "rgb(var(--brand-100) / <alpha-value>)",
          200: "rgb(var(--brand-200) / <alpha-value>)",
          300: "rgb(var(--brand-300) / <alpha-value>)",
          400: "rgb(var(--brand-400) / <alpha-value>)",
          500: "rgb(var(--brand-500) / <alpha-value>)",
          600: "rgb(var(--brand-600) / <alpha-value>)",
          700: "rgb(var(--brand-700) / <alpha-value>)",
          800: "rgb(var(--brand-800) / <alpha-value>)",
          900: "rgb(var(--brand-900) / <alpha-value>)",
          950: "rgb(var(--brand-950) / <alpha-value>)",
        },
        success: {
          50: "rgb(var(--success-50) / <alpha-value>)",
          100: "rgb(var(--success-100) / <alpha-value>)",
          200: "rgb(var(--success-200) / <alpha-value>)",
          300: "rgb(var(--success-300) / <alpha-value>)",
          400: "rgb(var(--success-400) / <alpha-value>)",
          500: "rgb(var(--success-500) / <alpha-value>)",
          600: "rgb(var(--success-600) / <alpha-value>)",
          700: "rgb(var(--success-700) / <alpha-value>)",
          800: "rgb(var(--success-800) / <alpha-value>)",
          900: "rgb(var(--success-900) / <alpha-value>)",
          950: "rgb(var(--success-950) / <alpha-value>)",
        },
        danger: {
          50: "rgb(var(--danger-50) / <alpha-value>)",
          100: "rgb(var(--danger-100) / <alpha-value>)",
          200: "rgb(var(--danger-200) / <alpha-value>)",
          300: "rgb(var(--danger-300) / <alpha-value>)",
          400: "rgb(var(--danger-400) / <alpha-value>)",
          500: "rgb(var(--danger-500) / <alpha-value>)",
          600: "rgb(var(--danger-600) / <alpha-value>)",
          700: "rgb(var(--danger-700) / <alpha-value>)",
          800: "rgb(var(--danger-800) / <alpha-value>)",
          900: "rgb(var(--danger-900) / <alpha-value>)",
          950: "rgb(var(--danger-950) / <alpha-value>)",
        },
        warning: {
          50: "rgb(var(--warning-50) / <alpha-value>)",
          100: "rgb(var(--warning-100) / <alpha-value>)",
          200: "rgb(var(--warning-200) / <alpha-value>)",
          300: "rgb(var(--warning-300) / <alpha-value>)",
          400: "rgb(var(--warning-400) / <alpha-value>)",
          500: "rgb(var(--warning-500) / <alpha-value>)",
          600: "rgb(var(--warning-600) / <alpha-value>)",
          700: "rgb(var(--warning-700) / <alpha-value>)",
          800: "rgb(var(--warning-800) / <alpha-value>)",
          900: "rgb(var(--warning-900) / <alpha-value>)",
          950: "rgb(var(--warning-950) / <alpha-value>)",
        },
        caution: {
          50: "rgb(var(--caution-50) / <alpha-value>)",
          100: "rgb(var(--caution-100) / <alpha-value>)",
          200: "rgb(var(--caution-200) / <alpha-value>)",
          300: "rgb(var(--caution-300) / <alpha-value>)",
          400: "rgb(var(--caution-400) / <alpha-value>)",
          500: "rgb(var(--caution-500) / <alpha-value>)",
          600: "rgb(var(--caution-600) / <alpha-value>)",
          700: "rgb(var(--caution-700) / <alpha-value>)",
          800: "rgb(var(--caution-800) / <alpha-value>)",
          900: "rgb(var(--caution-900) / <alpha-value>)",
          950: "rgb(var(--caution-950) / <alpha-value>)",
        },
        info: {
          50: "rgb(var(--info-50) / <alpha-value>)",
          100: "rgb(var(--info-100) / <alpha-value>)",
          200: "rgb(var(--info-200) / <alpha-value>)",
          300: "rgb(var(--info-300) / <alpha-value>)",
          400: "rgb(var(--info-400) / <alpha-value>)",
          500: "rgb(var(--info-500) / <alpha-value>)",
          600: "rgb(var(--info-600) / <alpha-value>)",
          700: "rgb(var(--info-700) / <alpha-value>)",
          800: "rgb(var(--info-800) / <alpha-value>)",
          900: "rgb(var(--info-900) / <alpha-value>)",
          950: "rgb(var(--info-950) / <alpha-value>)",
        },
        accent: {
          // shadcn's accent + the numeric ramp share one key. They used to be
          // two separate `accent:` entries, and the later one silently deleted
          // the ramp — 79 accent-NNN classes were emitting no CSS at all.
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          50: "rgb(var(--accent-50) / <alpha-value>)",
          100: "rgb(var(--accent-100) / <alpha-value>)",
          200: "rgb(var(--accent-200) / <alpha-value>)",
          300: "rgb(var(--accent-300) / <alpha-value>)",
          400: "rgb(var(--accent-400) / <alpha-value>)",
          500: "rgb(var(--accent-500) / <alpha-value>)",
          600: "rgb(var(--accent-600) / <alpha-value>)",
          700: "rgb(var(--accent-700) / <alpha-value>)",
          800: "rgb(var(--accent-800) / <alpha-value>)",
          900: "rgb(var(--accent-900) / <alpha-value>)",
          950: "rgb(var(--accent-950) / <alpha-value>)",
        },
        positive: {
          50: "rgb(var(--positive-50) / <alpha-value>)",
          100: "rgb(var(--positive-100) / <alpha-value>)",
          200: "rgb(var(--positive-200) / <alpha-value>)",
          300: "rgb(var(--positive-300) / <alpha-value>)",
          400: "rgb(var(--positive-400) / <alpha-value>)",
          500: "rgb(var(--positive-500) / <alpha-value>)",
          600: "rgb(var(--positive-600) / <alpha-value>)",
          700: "rgb(var(--positive-700) / <alpha-value>)",
          800: "rgb(var(--positive-800) / <alpha-value>)",
          900: "rgb(var(--positive-900) / <alpha-value>)",
          950: "rgb(var(--positive-950) / <alpha-value>)",
        },
        alert: {
          50: "rgb(var(--alert-50) / <alpha-value>)",
          100: "rgb(var(--alert-100) / <alpha-value>)",
          200: "rgb(var(--alert-200) / <alpha-value>)",
          300: "rgb(var(--alert-300) / <alpha-value>)",
          400: "rgb(var(--alert-400) / <alpha-value>)",
          500: "rgb(var(--alert-500) / <alpha-value>)",
          600: "rgb(var(--alert-600) / <alpha-value>)",
          700: "rgb(var(--alert-700) / <alpha-value>)",
          800: "rgb(var(--alert-800) / <alpha-value>)",
          900: "rgb(var(--alert-900) / <alpha-value>)",
          950: "rgb(var(--alert-950) / <alpha-value>)",
        },
        aqua: {
          50: "rgb(var(--aqua-50) / <alpha-value>)",
          100: "rgb(var(--aqua-100) / <alpha-value>)",
          200: "rgb(var(--aqua-200) / <alpha-value>)",
          300: "rgb(var(--aqua-300) / <alpha-value>)",
          400: "rgb(var(--aqua-400) / <alpha-value>)",
          500: "rgb(var(--aqua-500) / <alpha-value>)",
          600: "rgb(var(--aqua-600) / <alpha-value>)",
          700: "rgb(var(--aqua-700) / <alpha-value>)",
          800: "rgb(var(--aqua-800) / <alpha-value>)",
          900: "rgb(var(--aqua-900) / <alpha-value>)",
          950: "rgb(var(--aqua-950) / <alpha-value>)",
        },
        blush: {
          50: "rgb(var(--blush-50) / <alpha-value>)",
          100: "rgb(var(--blush-100) / <alpha-value>)",
          200: "rgb(var(--blush-200) / <alpha-value>)",
          300: "rgb(var(--blush-300) / <alpha-value>)",
          400: "rgb(var(--blush-400) / <alpha-value>)",
          500: "rgb(var(--blush-500) / <alpha-value>)",
          600: "rgb(var(--blush-600) / <alpha-value>)",
          700: "rgb(var(--blush-700) / <alpha-value>)",
          800: "rgb(var(--blush-800) / <alpha-value>)",
          900: "rgb(var(--blush-900) / <alpha-value>)",
          950: "rgb(var(--blush-950) / <alpha-value>)",
        },
        magenta: {
          50: "rgb(var(--magenta-50) / <alpha-value>)",
          100: "rgb(var(--magenta-100) / <alpha-value>)",
          200: "rgb(var(--magenta-200) / <alpha-value>)",
          300: "rgb(var(--magenta-300) / <alpha-value>)",
          400: "rgb(var(--magenta-400) / <alpha-value>)",
          500: "rgb(var(--magenta-500) / <alpha-value>)",
          600: "rgb(var(--magenta-600) / <alpha-value>)",
          700: "rgb(var(--magenta-700) / <alpha-value>)",
          800: "rgb(var(--magenta-800) / <alpha-value>)",
          900: "rgb(var(--magenta-900) / <alpha-value>)",
          950: "rgb(var(--magenta-950) / <alpha-value>)",
        },
        sand: {
          50: "rgb(var(--sand-50) / <alpha-value>)",
          100: "rgb(var(--sand-100) / <alpha-value>)",
          200: "rgb(var(--sand-200) / <alpha-value>)",
          300: "rgb(var(--sand-300) / <alpha-value>)",
          400: "rgb(var(--sand-400) / <alpha-value>)",
          500: "rgb(var(--sand-500) / <alpha-value>)",
          600: "rgb(var(--sand-600) / <alpha-value>)",
          700: "rgb(var(--sand-700) / <alpha-value>)",
          800: "rgb(var(--sand-800) / <alpha-value>)",
          900: "rgb(var(--sand-900) / <alpha-value>)",
          950: "rgb(var(--sand-950) / <alpha-value>)",
        },
        // Semantic aliases — see the Layer 2 block in src/index.css
        surface: {
          DEFAULT: "rgb(var(--color-surface) / <alpha-value>)",
          sunken: "rgb(var(--color-surface-sunken) / <alpha-value>)",
          inverted: "rgb(var(--color-surface-inverted) / <alpha-value>)",
          "inverted-deep":
            "rgb(var(--color-surface-inverted-deep) / <alpha-value>)",
        },
        content: {
          DEFAULT: "rgb(var(--color-text-primary) / <alpha-value>)",
          body: "rgb(var(--color-text-body) / <alpha-value>)",
          muted: "rgb(var(--color-text-muted) / <alpha-value>)",
          subtle: "rgb(var(--color-text-subtle) / <alpha-value>)",
          inverted: "rgb(var(--color-text-inverted) / <alpha-value>)",
        },
        line: {
          DEFAULT: "rgb(var(--color-border) / <alpha-value>)",
          subtle: "rgb(var(--color-border-subtle) / <alpha-value>)",
          strong: "rgb(var(--color-border-strong) / <alpha-value>)",
          hover: "rgb(var(--color-border-hover) / <alpha-value>)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
