import { localDataEngine } from "@/api/localDataEngine";
import { seedAllDataForUser } from "@/entities/seedData";
import { supabase } from "./supabaseClient";
import { Client } from "@/entities/Client";
import { Invoice } from "@/entities/Invoice";
import { Quote } from "@/entities/Quote";
import { Job } from "@/entities/Job";
import { JobPhoto } from "@/entities/JobPhoto";
import { JobMaterial } from "@/entities/JobMaterial";
import { JobNote } from "@/entities/JobNote";
import { BusinessSettings } from "@/entities/BusinessSettings";
import { Subscription } from "@/entities/Subscription";
import { RecurringInvoice } from "@/entities/RecurringInvoice";
import { InvoiceTemplate } from "@/entities/InvoiceTemplate";
import { Receipt } from "@/entities/Receipt";
import { buildLoginUrl } from "@/lib/auth-redirects";

function buildPDFBlobUrl(title) {
  const html = `
    <html>
      <head><title>${title}</title>
      <style>
        body { font-family: Inter, -apple-system, sans-serif; padding: 40px; color: #333; }
        h1 { color: #10b981; }
        .footer { margin-top: 40px; font-size: 12px; color: #888; }
      </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p>This is a preview PDF generated locally.</p>
        <div class="footer">Generated by Invoicium (local mode)</div>
      </body>
    </html>
  `;
  const blob = new Blob([html], { type: "text/html" });
  return URL.createObjectURL(blob);
}

function safeParseJSON(s) {
  try { return JSON.parse(s); } catch { return []; }
}

async function enrichBusinessContext(base = {}) {
  try {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return base;
    const { data: settingsRows } = await supabase
      .from("BusinessSettings")
      .select("business_name, email, phone, address, website")
      .eq("user_id", user.id)
      .limit(1);
    const s = (settingsRows && settingsRows[0]) || {};
    return {
      business_name: base.business_name || s.business_name || "Invoicium",
      sender_name: base.sender_name || user.user_metadata?.full_name || user.email || s.business_name || "Invoicium",
      sender_email: base.sender_email || s.email || user.email || null,
      sender_phone: base.sender_phone || s.phone || null,
      sender_address: base.sender_address || s.address || null,
      sender_website: base.sender_website || s.website || null,
    };
  } catch {
    return base;
  }
}

async function loadInvoiceById(invoice_id) {
  if (!invoice_id) return null;
  try {
    const { data } = await supabase.from("Invoice").select("*").eq("id", invoice_id).maybeSingle();
    return data || null;
  } catch {
    return null;
  }
}

async function loadQuoteById(quote_id) {
  if (!quote_id) return null;
  try {
    const { data } = await supabase.from("Quote").select("*").eq("id", quote_id).maybeSingle();
    return data || null;
  } catch {
    return null;
  }
}

async function normalizeSendPayload(name, payload) {
  const p = { ...payload };
  const ctx = await enrichBusinessContext(p);

  if (name === "sendInvoiceEmail" || name === "sendQuoteEmail") {
    p.to = p.to || p.client_email || p.email;
  }
  if (name === "sendInvoiceSMS" || name === "sendQuoteSMS") {
    p.to = p.to || p.client_phone || p.phone;
  }

  // Fall back to DB lookup for contact + totals when only the id was passed, and
  // always enrich items/dates so the nicer email template has everything it needs.
  if (name === "sendInvoiceEmail" || name === "sendInvoiceSMS") {
    const inv = p.invoice_id ? await loadInvoiceById(p.invoice_id) : null;
    if (inv) {
      p.to = p.to || (name === "sendInvoiceEmail" ? inv.client_email : inv.client_phone);
      p.invoice_number = p.invoice_number || inv.invoice_number;
      p.client_name = p.client_name || inv.client_name;
      p.total = p.total != null ? p.total : inv.total;
      p.subtotal = p.subtotal != null ? p.subtotal : inv.subtotal;
      p.tax_rate = p.tax_rate != null ? p.tax_rate : inv.tax_rate;
      p.tax_amount = p.tax_amount != null ? p.tax_amount : inv.tax_amount;
      p.items = p.items || (Array.isArray(inv.items) ? inv.items : (typeof inv.items === "string" ? safeParseJSON(inv.items) : []));
      p.pdf_url = p.pdf_url || inv.pdf_url;
      p.notes = p.notes || inv.notes;
      p.due_date = p.due_date || inv.due_date;
      p.issue_date = p.issue_date || inv.issue_date || inv.created_date;
      p.created_date = p.created_date || inv.created_date;
      p.status = p.status || inv.status;
    }
  }
  if (name === "sendQuoteEmail" || name === "sendQuoteSMS") {
    const q = p.quote_id ? await loadQuoteById(p.quote_id) : null;
    if (q) {
      p.to = p.to || (name === "sendQuoteEmail" ? q.client_email : q.client_phone);
      p.quote_number = p.quote_number || q.quote_number;
      p.client_name = p.client_name || q.client_name;
      p.total = p.total != null ? p.total : q.total;
      p.subtotal = p.subtotal != null ? p.subtotal : q.subtotal;
      p.tax_rate = p.tax_rate != null ? p.tax_rate : q.tax_rate;
      p.tax_amount = p.tax_amount != null ? p.tax_amount : q.tax_amount;
      p.items = p.items || (Array.isArray(q.items) ? q.items : (typeof q.items === "string" ? safeParseJSON(q.items) : []));
      p.pdf_url = p.pdf_url || q.pdf_url;
      p.notes = p.notes || q.notes;
      p.expiry_date = p.expiry_date || q.expiry_date;
      p.date_issued = p.date_issued || q.date_issued || q.created_date;
      p.created_date = p.created_date || q.created_date;
    }
  }

  return { ...p, ...ctx };
}

async function handleFunctionInvoke(name, payload = {}) {
  const realEdgeFunctions = {
    generateInvoicePDF: 'generate-invoice-pdf',
    generateQuotePDF: 'generate-quote-pdf',
    sendInvoiceEmail: 'send-invoice-email',
    sendQuoteEmail: 'send-quote-email',
    sendInvoiceSMS: 'send-invoice-sms',
    sendQuoteSMS: 'send-quote-sms',
    createInvoicePaymentLink: 'create-invoice-payment-link',
    connectGoogleCalendar: 'google-calendar-auth-url',
    syncJobToGoogleCalendar: 'google-calendar-sync-job',
    fetchGoogleCalendarEvents: 'google-calendar-events',
    checkOverdueInvoices: 'check-overdue-invoices',
    sendTestAnalyticsEmail: 'send-test-analytics-email',
    stripeCreateSession: 'stripe-create-session',
    stripeCreateSubscription: 'stripe-create-subscription',
    confirmAndActivate: 'confirm-and-activate',
  };

  // Only invoice/quote send functions need the client-contact normalizer. Crew
  // invites and test analytics emails resolve the recipient on the server side.
  const needsSendNormalize = (n) =>
    n === "sendInvoiceEmail" ||
    n === "sendQuoteEmail" ||
    n === "sendInvoiceSMS" ||
    n === "sendQuoteSMS";

  if (realEdgeFunctions[name]) {
    let body = payload;
    if (needsSendNormalize(name)) {
      body = await normalizeSendPayload(name, payload);
      if (!body.to) {
        const kind = name.includes("Email") ? "email" : "phone";
        return { data: { success: false, error: `Missing recipient ${kind}` } };
      }
    }
    try {
      const { data, error } = await supabase.functions.invoke(realEdgeFunctions[name], { body });
      if (error) {
        const serverMsg = data?.error || error.message || String(error);
        console.error(`Edge function ${name} failed:`, serverMsg, data);
        return { data: { success: false, error: serverMsg } };
      }
      if (data && data.error) {
        return { data: { success: false, error: data.error } };
      }
      return { data: { success: true, ...(data || {}) } };
    } catch (e) {
      console.error(`Edge function ${name} threw:`, e);
      return { data: { success: false, error: e.message || String(e) } };
    }
  }

  console.log(`[Function Stub] ${name}`, payload);

  if (name === "saveNotificationSettings") {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return { data: { success: false, error: "Not authenticated" } };
      const allowed = [
        "analytics_email_frequency",
        "analytics_email_day",
        "analytics_email_time",
        "send_review_requests",
        "notification_preferences",
      ];
      const patch = {};
      for (const k of allowed) if (payload[k] !== undefined) patch[k] = payload[k];

      const { data: existing } = await supabase
        .from("BusinessSettings")
        .select("id")
        .eq("user_id", user.id)
        .limit(1);

      if (existing && existing.length) {
        await supabase.from("BusinessSettings").update(patch).eq("id", existing[0].id);
      } else {
        await supabase.from("BusinessSettings").insert([{ user_id: user.id, ...patch }]);
      }
      return { data: { success: true } };
    } catch (e) {
      return { data: { success: false, error: e.message || String(e) } };
    }
  }

  if (name === "checkOverdueInvoices") {
    const invoices = await localDataEngine.list("Invoice");
    let updated = 0;
    const now = new Date();
    for (const inv of invoices) {
      if (inv.status === "sent" && inv.due_date && new Date(inv.due_date) < now) {
        await localDataEngine.update("Invoice", inv.id, { status: "overdue" });
        updated++;
      }
    }
    return { data: { success: true, updated_count: updated } };
  }

  if (name === "generateInvoicePDF" || name === "generateQuotePDF") {
    const title = name === "generateInvoicePDF" ? "Invoice Preview" : "Quote Preview";
    return { data: { pdf_url: buildPDFBlobUrl(title), success: true } };
  }

  if (name === "sendOverdueNotification") {
    return { data: { success: true } };
  }

  if (name === "notifyInvoiceCreated" || name === "notifyQuoteCreated" || name === "notifyQuoteApproval" || name === "notifyQuoteResponse") {
    return { data: { success: true } };
  }

  if (name === "sendQuoteEmail" || name === "sendQuoteSMS" || name === "sendInvoiceEmail" || name === "sendInvoiceSMS") {
    return { data: { success: true } };
  }

  if (name === "exportInvoicesToExcel" || name === "exportQuotesToExcel") {
    return { data: { success: true } };
  }

  if (name === "getStripeCustomerPortal" || name === "createCheckoutSession" || name === "confirmCheckoutSession") {
    return { data: { success: true, url: "#" } };
  }

  if (name === "connectGoogleCalendar" || name === "syncJobToGoogleCalendar" || name === "fetchGoogleCalendarEvents") {
    return { data: { success: true } };
  }

  if (name === "getAvailableSlots" || name === "suggestOptimalTime") {
    return { data: { slots: [] } };
  }

  if (name === "createBooking") {
    return { data: { success: true, booking_id: "bk_" + Date.now() } };
  }

  if (name === "sendContactEmail") {
    return { data: { success: true } };
  }

  if (name === "searchProductPrices") {
    return { data: { results: [] } };
  }

  if (name === "saveNotificationSettings") {
    return { data: { success: true } };
  }

  if (name === "getBillingHistory") {
    return { data: { history: [] } };
  }

  if (name === "seedServicePresets") {
    return { data: { success: true } };
  }

  if (name === "sendWelcomeEmail" || name === "sendWeeklyAnalytics" || name === "sendTestAnalyticsEmail") {
    return { data: { success: true } };
  }

  if (name === "purchaseInvoicePack" || name === "fixSubscriptionLimits") {
    return { data: { success: true } };
  }

  if (name === "getStripeCustomerLocation") {
    return { data: { country: "US" } };
  }

  if (name === "stripeCreateSession" || name === "stripeWebhook" || name === "createStripeConnectAccount" || name === "debugStripe" || name === "debugStripeSession") {
    return { data: { success: true } };
  }

  if (name === "checkStripeStatus") {
    return { data: { status: "active" } };
  }

  if (name === "invoicePaymentWebhook" || name === "invoicePackWebhook") {
    return { data: { received: true } };
  }

  if (name === "confirmAndActivate" || name === "forceActivate") {
    return { data: { success: true } };
  }

  if (name === "sendPhoneVerification" || name === "verifyPhoneCode") {
    return { data: { success: true } };
  }

  if (name === "assignAppointment") {
    return { data: { success: true } };
  }

  if (name === "createInvoicePaymentLink") {
    return { data: { success: true, payment_link: "#" } };
  }

  if (name === "getInvoiceBySession") {
    return { data: { success: true, invoice_number: "INV-000", total: 0, pdf_url: null } };
  }

  return { data: { success: true } };
}

async function invokeLLM({ prompt, response_json_schema }) {
  console.log("[LLM Stub] Prompt received, returning generic line items");
  const items = [
    { description: "Labor", quantity: 4, rate: 85 },
    { description: "Materials", quantity: 1, rate: 240 },
  ];
  return { items };
}

export const sdk = {
  auth: {
    me: async () => {
      const { data: { user }, error } = await supabase.auth.getUser();
      if (error || !user) return null;

      // Ensure fallback demo data exists for this user locally
      seedAllDataForUser(user.id);

      // Try to fetch extended profile from Supabase (ignore if table missing or row not found)
      let profile = null;
      try {
        const { data, error } = await supabase
          .from("profiles")
          .select("*")
          .eq("id", user.id)
          .maybeSingle();
        if (error && error.code !== 'PGRST116') throw error;
        profile = data;
      } catch (profileError) {
        // Table doesn't exist yet or no profile row — that's okay, use auth metadata
      }

      return {
        id: user.id,
        email: user.email,
        full_name: profile?.full_name || user.user_metadata?.full_name || "",
        onboarding_completed: profile?.onboarding_completed || false,
        role: profile?.role || "admin",
        ...profile,
      };
    },
    logout: async () => {
      await supabase.auth.signOut();
      localStorage.removeItem("invoicium_user");
      window.location.href = "/";
    },
    redirectToLogin: (returnUrl) => {
      window.location.href = buildLoginUrl(returnUrl);
    },
    isAuthenticated: async () => {
      const { data: { session } } = await supabase.auth.getSession();
      return Boolean(session);
    },
    signInWithGoogle: async (returnUrl) => {
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: "google",
        options: {
          redirectTo: buildLoginUrl(returnUrl),
          queryParams: {
            prompt: "select_account",
          },
        },
      });
      if (error) throw error;
      return data;
    },
    register: async ({ email, password, ...metadata }) => {
      const { data, error } = await supabase.auth.signUp({
        email,
        password,
        options: { data: metadata },
      });
      if (error) throw error;
      return data.user;
    },
    updateMe: async (updates) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");
      const { error } = await supabase.from("profiles").update(updates).eq("id", user.id);
      if (error) throw error;
      return { ...user, ...updates };
    },
  },
  entities: {
    Client,
    Invoice,
    Quote,
    Job,
    JobPhoto,
    JobMaterial,
    JobNote,
    BusinessSettings,
    Subscription,
    RecurringInvoice,
    InvoiceTemplate,
    Receipt,
    // Aliases for any legacy references
    Query: {
      list: () => Promise.resolve([]),
    },
    UserSpecialty: {
      filter: () => Promise.resolve([{ user_id: null, primary_specialty: "general" }]),
      create: (p) => localDataEngine.create("UserSpecialty", p),
      update: (id, p) => localDataEngine.update("UserSpecialty", id, p),
    },
    JobExpense: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("JobExpense", p),
      update: (id, p) => localDataEngine.update("JobExpense", id, p),
    },
    Notification: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("Notification", p),
      update: (id, p) => localDataEngine.update("Notification", id, p),
      delete: (id) => localDataEngine.delete("Notification", id),
      subscribe: () => {
        return () => {};
      },
    },
    Review: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("Review", p),
    },
    ContractorListing: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("ContractorListing", p),
      update: (id, p) => localDataEngine.update("ContractorListing", id, p),
    },
    Appointment: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("Appointment", p),
      update: (id, p) => localDataEngine.update("Appointment", id, p),
      delete: (id) => localDataEngine.delete("Appointment", id),
    },
    ServicePreset: {
      filter: () => Promise.resolve([
        { id: "sp_1", name: "Handyman Service", is_system: true, items: [{ description: "General labor", quantity: 1, rate: 75 }] },
        { id: "sp_2", name: "Painting", is_system: true, items: [{ description: "Interior painting", quantity: 1, rate: 450 }] },
        { id: "sp_3", name: "Plumbing Repair", is_system: true, items: [{ description: "Plumbing fix", quantity: 1, rate: 120 }] },
      ]),
      create: (p) => localDataEngine.create("ServicePreset", p),
      update: (id, p) => localDataEngine.update("ServicePreset", id, p),
    },
    CustomServiceTemplate: {
      filter: (filters, sort, limit) => localDataEngine.list("CustomServiceTemplate", filters, sort, limit),
      list: (filters, sort, limit) => localDataEngine.list("CustomServiceTemplate", filters, sort, limit),
      create: (p) => localDataEngine.create("CustomServiceTemplate", p),
      update: (id, p) => localDataEngine.update("CustomServiceTemplate", id, p),
      delete: (id) => localDataEngine.delete("CustomServiceTemplate", id),
    },
    TaskNote: {
      filter: (filters, sort, limit) => localDataEngine.list("TaskNote", filters, sort, limit),
      create: (p) => localDataEngine.create("TaskNote", p),
      update: (id, p) => localDataEngine.update("TaskNote", id, p),
      delete: (id) => localDataEngine.delete("TaskNote", id),
    },
    JobPhotoShare: {
      filter: (filters, sort, limit) => localDataEngine.list("JobPhotoShare", filters, sort, limit),
      create: (p) => localDataEngine.create("JobPhotoShare", p),
      update: (id, p) => localDataEngine.update("JobPhotoShare", id, p),
      delete: (id) => localDataEngine.delete("JobPhotoShare", id),
    },
  },
  functions: {
    invoke: handleFunctionInvoke,
  },
  appLogs: {
    logUserInApp: () => Promise.resolve(),
  },
  integrations: {
    Core: {
      InvokeLLM: invokeLLM,
      SendEmail: () => Promise.resolve({ success: true }),
      SendSMS: () => Promise.resolve({ success: true }),
      UploadFile: (file) => Promise.resolve({ url: URL.createObjectURL(file), success: true }),
      GenerateImage: () => Promise.resolve({ url: "https://placehold.co/600x400?text=Generated+Image" }),
      ExtractDataFromUploadedFile: () => Promise.resolve({ data: {} }),
    },
  },
};

export default sdk;
