import { localDataEngine } from "@/api/localDataEngine";
import { seedAllDataForUser } from "@/entities/seedData";
import { supabase } from "./supabaseClient";
import { Client } from "@/entities/Client";
import { Invoice } from "@/entities/Invoice";
import { Quote } from "@/entities/Quote";
import { Job } from "@/entities/Job";
import { JobPhoto } from "@/entities/JobPhoto";
import { JobMaterial } from "@/entities/JobMaterial";
import { JobNote } from "@/entities/JobNote";
import { BusinessSettings } from "@/entities/BusinessSettings";
import { Subscription } from "@/entities/Subscription";
import { RecurringInvoice } from "@/entities/RecurringInvoice";
import { InvoiceTemplate } from "@/entities/InvoiceTemplate";
import { Receipt } from "@/entities/Receipt";
import { EmployeeProfile } from "@/entities/EmployeeProfile";
import { CrewInvite } from "@/entities/CrewInvite";
import { CrewMemberSettings } from "@/entities/CrewMemberSettings";
import { TimeEntry } from "@/entities/TimeEntry";
import { buildLoginUrl } from "@/lib/auth-redirects";

function buildPDFBlobUrl(title) {
  const html = `
    <html>
      <head><title>${title}</title>
      <style>
        body { font-family: Inter, -apple-system, sans-serif; padding: 40px; color: #333; }
        h1 { color: #10b981; }
        .footer { margin-top: 40px; font-size: 12px; color: #888; }
      </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p>This is a preview PDF generated locally.</p>
        <div class="footer">Generated by Invoicium (local mode)</div>
      </body>
    </html>
  `;
  const blob = new Blob([html], { type: "text/html" });
  return URL.createObjectURL(blob);
}

/**
 * Upload a file to Supabase Storage and return a URL that survives a reload.
 *
 * This replaces a stub that did `URL.createObjectURL(file)`. Three things were
 * wrong with it, and all five call sites hit all three:
 *
 *   1. Every caller invokes it as UploadFile({ file }), an OBJECT. Passing that
 *      to createObjectURL throws "Overload resolution failed" -- a TypeError,
 *      not a rejected promise -- which is what surfaced on Settings as the
 *      generic "Failed to save settings. Please try again."
 *   2. Every caller reads `.file_url`; the stub returned `.url`. So even when
 *      it did not throw, the result was undefined.
 *   3. A blob: URL is local to the tab that made it and dies on reload. Nothing
 *      was ever uploaded anywhere, so a logo could never have persisted.
 *
 * Objects are keyed <user_id>/<uuid>-<name>: the first segment is what the
 * storage policies use to confine a user to their own folder, and the uuid
 * makes the URL unguessable, which is what makes a public-read bucket
 * acceptable for logos that have to render inside emailed PDFs.
 *
 * Returns both `file_url` and `url` -- callers here use the former, but the
 * name `url` is what the stub returned and what any future caller is likely to
 * reach for.
 *
 * @param {File|Blob|{file: File|Blob}} input
 * @returns {Promise<{file_url: string|null, url: string|null, path?: string,
 *                    success: boolean, error?: string}>}
 */
async function uploadFile(input) {
  // Accept both shapes. Every current caller passes { file }, but the exported
  // name reads like it takes a file, and one day someone will pass one.
  const file = input && typeof input === "object" && "file" in input ? input.file : input;

  if (!file) {
    return { file_url: null, url: null, success: false, error: "No file provided" };
  }

  try {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return { file_url: null, url: null, success: false, error: "Not signed in" };
    }

    // Strip anything that would make a messy or ambiguous object key. Keeping
    // the original extension matters: Storage serves Content-Type from it, and
    // an <img> pointed at an extensionless object renders as a broken icon.
    const rawName = String(file.name || "upload").split(/[\\/]/).pop();
    const safeName = rawName.replace(/[^A-Za-z0-9._-]/g, "_").slice(-80);
    const unique =
      globalThis.crypto?.randomUUID?.() ??
      `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`;
    const path = `${user.id}/${unique}-${safeName}`;

    const { error } = await supabase.storage.from("uploads").upload(path, file, {
      cacheControl: "3600",
      upsert: false,
      contentType: file.type || undefined,
    });
    if (error) throw error;

    const {
      data: { publicUrl },
    } = supabase.storage.from("uploads").getPublicUrl(path);

    return { file_url: publicUrl, url: publicUrl, path, success: true };
  } catch (e) {
    console.error("UploadFile failed:", e);
    // Reported rather than thrown: callers check `success`/`file_url`, and a
    // throw here aborts a whole settings save over one image.
    return {
      file_url: null,
      url: null,
      success: false,
      error: e?.message || String(e),
    };
  }
}

function safeParseJSON(s) {
  try {
    return JSON.parse(s);
  } catch {
    return [];
  }
}

async function enrichBusinessContext(base = {}) {
  try {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return base;
    const { data: settingsRows } = await supabase
      .from("BusinessSettings")
      .select("business_name, email, phone, address, website")
      .eq("user_id", user.id)
      .limit(1);
    const s = (settingsRows && settingsRows[0]) || {};
    return {
      business_name: base.business_name || s.business_name || "Invoicium",
      sender_name:
        base.sender_name ||
        user.user_metadata?.full_name ||
        user.email ||
        s.business_name ||
        "Invoicium",
      sender_email: base.sender_email || s.email || user.email || null,
      sender_phone: base.sender_phone || s.phone || null,
      sender_address: base.sender_address || s.address || null,
      sender_website: base.sender_website || s.website || null,
    };
  } catch {
    return base;
  }
}

async function loadInvoiceById(invoice_id) {
  if (!invoice_id) return null;
  try {
    const { data } = await supabase
      .from("Invoice")
      .select("*")
      .eq("id", invoice_id)
      .maybeSingle();
    return data || null;
  } catch {
    return null;
  }
}

async function loadQuoteById(quote_id) {
  if (!quote_id) return null;
  try {
    const { data } = await supabase
      .from("Quote")
      .select("*")
      .eq("id", quote_id)
      .maybeSingle();
    return data || null;
  } catch {
    return null;
  }
}

async function normalizeSendPayload(name, payload) {
  const p = { ...payload };
  const ctx = await enrichBusinessContext(p);

  if (name === "sendInvoiceEmail" || name === "sendQuoteEmail") {
    p.to = p.to || p.client_email || p.email;
  }
  if (name === "sendInvoiceSMS" || name === "sendQuoteSMS") {
    p.to = p.to || p.client_phone || p.phone;
  }

  // Fall back to DB lookup for contact + totals when only the id was passed, and
  // always enrich items/dates so the nicer email template has everything it needs.
  if (name === "sendInvoiceEmail" || name === "sendInvoiceSMS") {
    const inv = p.invoice_id ? await loadInvoiceById(p.invoice_id) : null;
    if (inv) {
      p.to =
        p.to ||
        (name === "sendInvoiceEmail" ? inv.client_email : inv.client_phone);
      p.invoice_number = p.invoice_number || inv.invoice_number;
      p.client_name = p.client_name || inv.client_name;
      p.total = p.total != null ? p.total : inv.total;
      p.subtotal = p.subtotal != null ? p.subtotal : inv.subtotal;
      p.tax_rate = p.tax_rate != null ? p.tax_rate : inv.tax_rate;
      p.tax_amount = p.tax_amount != null ? p.tax_amount : inv.tax_amount;
      p.items =
        p.items ||
        (Array.isArray(inv.items)
          ? inv.items
          : typeof inv.items === "string"
            ? safeParseJSON(inv.items)
            : []);
      p.pdf_url = p.pdf_url || inv.pdf_url;
      p.notes = p.notes || inv.notes;
      p.due_date = p.due_date || inv.due_date;
      p.issue_date = p.issue_date || inv.issue_date || inv.created_date;
      p.created_date = p.created_date || inv.created_date;
      p.status = p.status || inv.status;
    }
  }
  if (name === "sendQuoteEmail" || name === "sendQuoteSMS") {
    const q = p.quote_id ? await loadQuoteById(p.quote_id) : null;
    if (q) {
      p.to =
        p.to || (name === "sendQuoteEmail" ? q.client_email : q.client_phone);
      p.quote_number = p.quote_number || q.quote_number;
      p.client_name = p.client_name || q.client_name;
      p.total = p.total != null ? p.total : q.total;
      p.subtotal = p.subtotal != null ? p.subtotal : q.subtotal;
      p.tax_rate = p.tax_rate != null ? p.tax_rate : q.tax_rate;
      p.tax_amount = p.tax_amount != null ? p.tax_amount : q.tax_amount;
      p.items =
        p.items ||
        (Array.isArray(q.items)
          ? q.items
          : typeof q.items === "string"
            ? safeParseJSON(q.items)
            : []);
      p.pdf_url = p.pdf_url || q.pdf_url;
      p.notes = p.notes || q.notes;
      p.expiry_date = p.expiry_date || q.expiry_date;
      p.date_issued = p.date_issued || q.date_issued || q.created_date;
      p.created_date = p.created_date || q.created_date;
    }
  }

  return { ...p, ...ctx };
}

/**
 * The honest answer for a function that was never built.
 *
 * Every one of these used to return { success: true }. That is how quote
 * approval shipped a green "Quote Approved!" for a quote nobody approved, and
 * how the Contact form has been telling people their message was sent while
 * discarding it. A stub may do nothing; it may not claim it did something.
 *
 * Returns rather than throws, deliberately: every caller here follows "this
 * never throws, check .success", and several do not wrap the call in try at
 * all, so throwing would take those pages down instead of showing a message.
 *
 * `not_implemented` is separate from `error` so a caller can tell "not built
 * yet" from "tried and failed" and say the honest one to the user.
 */
function notImplemented(name) {
  console.warn(`[sdk] ${name} is not implemented; returning failure.`);
  return {
    data: { success: false, error: "not_implemented", not_implemented: true },
  };
}

async function handleFunctionInvoke(name, payload = {}) {
  const realEdgeFunctions = {
    generateInvoicePDF: "generate-invoice-pdf",
    generateQuotePDF: "generate-quote-pdf",
    sendInvoiceEmail: "send-invoice-email",
    sendQuoteEmail: "send-quote-email",
    sendInvoiceSMS: "send-invoice-sms",
    sendQuoteSMS: "send-quote-sms",
    createInvoicePaymentLink: "create-invoice-payment-link",
    connectGoogleCalendar: "google-calendar-auth-url",
    syncJobToGoogleCalendar: "google-calendar-sync-job",
    fetchGoogleCalendarEvents: "google-calendar-events",
    checkOverdueInvoices: "check-overdue-invoices",
    sendTestAnalyticsEmail: "send-test-analytics-email",
    stripeCreateSession: "stripe-create-session",
    getStripeCustomerPortal: "stripe-customer-portal",
    cancelSubscription: "stripe-cancel-subscription",
    stripeCreateSubscription: "stripe-create-subscription",
    stripeValidatePromo: "stripe-validate-promo",
    createStripeConnectAccount: "stripe-connect-onboard",
    checkStripeStatus: "stripe-connect-status",
    confirmAndActivate: "confirm-and-activate",
    sendCrewInvite: "send-crew-invite",
    acceptCrewInvite: "accept-crew-invite",
    approveQuote: "approve-quote",
    invokeLLM: "invoke-llm",
    // The public document surface. These are the only functions here reachable
    // without a signed-in user: the public_token in the URL is the credential,
    // and the service role behind them is what makes an anonymous read possible
    // without loosening a single RLS policy.
    getPublicInvoice: "get-public-invoice",
    payPublicInvoice: "pay-public-invoice",
    getPublicQuote: "get-public-quote",
  };

  // Only invoice/quote send functions need the client-contact normalizer. Crew
  // invites and test analytics emails resolve the recipient on the server side.
  const needsSendNormalize = (n) =>
    n === "sendInvoiceEmail" ||
    n === "sendQuoteEmail" ||
    n === "sendInvoiceSMS" ||
    n === "sendQuoteSMS";

  if (realEdgeFunctions[name]) {
    let body = payload;
    if (needsSendNormalize(name)) {
      body = await normalizeSendPayload(name, payload);
      if (!body.to) {
        const kind = name.includes("Email") ? "email" : "phone";
        return { data: { success: false, error: `Missing recipient ${kind}` } };
      }
    }
    try {
      const { data, error } = await supabase.functions.invoke(
        realEdgeFunctions[name],
        { body },
      );
      if (error) {
        // On a non-2xx supabase-js hands back only "Edge Function returned a
        // non-2xx status code" and leaves data null -- the function's own
        // message is in the untouched Response on error.context. Read it, or
        // the user sees boilerplate instead of "That promo code is not valid."
        let payload = data;
        if (
          !payload &&
          error.context &&
          typeof error.context.json === "function"
        ) {
          try {
            payload = await error.context.json();
          } catch {
            payload = null;
          }
        }
        const serverMsg = payload?.error || error.message || String(error);
        console.error(`Edge function ${name} failed:`, serverMsg, payload);
        return {
          data: { success: false, ...(payload || {}), error: serverMsg },
        };
      }
      if (data && data.error) {
        return { data: { success: false, error: data.error } };
      }
      return { data: { success: true, ...(data || {}) } };
    } catch (e) {
      console.error(`Edge function ${name} threw:`, e);
      return { data: { success: false, error: e.message || String(e) } };
    }
  }

  console.log(`[Function Stub] ${name}`, payload);

  if (name === "saveNotificationSettings") {
    try {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user)
        return { data: { success: false, error: "Not authenticated" } };
      const allowed = [
        "analytics_email_frequency",
        "analytics_email_day",
        "analytics_email_time",
        "send_review_requests",
        "notification_preferences",
      ];
      const patch = {};
      for (const k of allowed)
        if (payload[k] !== undefined) patch[k] = payload[k];

      const { data: existing } = await supabase
        .from("BusinessSettings")
        .select("id")
        .eq("user_id", user.id)
        .limit(1);

      if (existing && existing.length) {
        await supabase
          .from("BusinessSettings")
          .update(patch)
          .eq("id", existing[0].id);
      } else {
        await supabase
          .from("BusinessSettings")
          .insert([{ user_id: user.id, ...patch }]);
      }
      return { data: { success: true } };
    } catch (e) {
      return { data: { success: false, error: e.message || String(e) } };
    }
  }

  if (name === "checkOverdueInvoices") {
    const invoices = await localDataEngine.list("Invoice");
    let updated = 0;
    const now = new Date();
    for (const inv of invoices) {
      if (
        inv.status === "sent" &&
        inv.due_date &&
        new Date(inv.due_date) < now
      ) {
        await localDataEngine.update("Invoice", inv.id, { status: "overdue" });
        updated++;
      }
    }
    return { data: { success: true, updated_count: updated } };
  }

  if (name === "generateInvoicePDF" || name === "generateQuotePDF") {
    const title =
      name === "generateInvoicePDF" ? "Invoice Preview" : "Quote Preview";
    return { data: { pdf_url: buildPDFBlobUrl(title), success: true } };
  }

  // Alerted that an overdue notification was sent, having sent nothing. This
  // is the product's central promise, so it is the highest-value one to build.
  if (name === "sendOverdueNotification") {
    return notImplemented(name);
  }

  // No user-facing claim -- callers only console.log. The contractor simply
  // never hears that an invoice went out.
  //
  // notifyQuoteApproval used to be in this list. Its only caller was
  // Quotes.jsx handleStatusChange, which logged "Notification response" and a
  // green tick for a function that has never existed, so a manual approve told
  // nobody. The caller is gone: a client's response now notifies through
  // approve-quote, and the contractor moving the dropdown themselves is not
  // news worth emailing them about.
  if (
    name === "notifyInvoiceCreated" ||
    name === "notifyQuoteCreated" ||
    name === "notifyQuoteResponse"
  ) {
    return notImplemented(name);
  }

  if (
    name === "sendQuoteEmail" ||
    name === "sendQuoteSMS" ||
    name === "sendInvoiceEmail" ||
    name === "sendInvoiceSMS"
  ) {
    return { data: { success: true } };
  }

  // Quotes.jsx does new Blob([response.data]) -- a success object produced a
  // file named .xlsx containing the text [object Object].
  if (name === "exportInvoicesToExcel" || name === "exportQuotesToExcel") {
    return notImplemented(name);
  }

  // getStripeCustomerPortal is a real Edge Function now (see realEdgeFunctions
  // above) -- it used to return url:'#', which is why the billing portal button
  // silently did nothing.
  if (name === "createCheckoutSession" || name === "confirmCheckoutSession") {
    return { data: { success: true, url: "#" } };
  }

  if (
    name === "connectGoogleCalendar" ||
    name === "syncJobToGoogleCalendar" ||
    name === "fetchGoogleCalendarEvents"
  ) {
    return { data: { success: true } };
  }

  // getAvailableSlots and createBooking are gone, along with the booking UI that
  // called them. Online booking was never built -- booking_slug and
  // available_hours are not even columns -- and createBooking used to invent a
  // booking_id so PublicBooking could render a confirmation for an appointment
  // that did not exist. The page now says so plainly instead.
  // See docs/feature-audit.md section 9.3.
  if (name === "suggestOptimalTime") {
    return notImplemented(name);
  }

  // Contact.jsx does not check .success at all, so the public contact form has
  // been showing message sent and discarding every message.
  if (name === "sendContactEmail") {
    return notImplemented(name);
  }

  if (name === "searchProductPrices") {
    return { data: { results: [] } };
  }

  // (A second saveNotificationSettings branch used to sit here returning
  // success:true. It was unreachable -- the real implementation above wins --
  // but it would have become the live answer the moment anyone reordered this
  // chain. Removed rather than left as a trap.)

  if (name === "getBillingHistory") {
    // Must match what Settings.jsx reads -- it renders .invoices and
    // .payment_methods. This used to return { history: [] }, a key nothing
    // consumes, which left both of those undefined and crashed the billing tab.
    return { data: { invoices: [], payment_methods: [] } };
  }

  if (name === "seedServicePresets") {
    return { data: { success: true } };
  }

  // sendTestAnalyticsEmail is a real edge function and never reaches here; it
  // stays in the condition only so removing that mapping cannot silently turn
  // it back into a lie. No welcome email has ever been sent.
  if (
    name === "sendWelcomeEmail" ||
    name === "sendWeeklyAnalytics" ||
    name === "sendTestAnalyticsEmail"
  ) {
    return notImplemented(name);
  }

  // fixSubscriptionLimits was removed with its Settings button -- the limits
  // were wrong at the source (stripe-webhook's stale table), not missing, so
  // there was nothing for it to repair.
  if (name === "purchaseInvoicePack") {
    return notImplemented(name);
  }

  if (name === "getStripeCustomerLocation") {
    return { data: { country: "US" } };
  }

  if (
    name === "stripeCreateSession" ||
    name === "stripeWebhook" ||
    name === "debugStripe" ||
    name === "debugStripeSession"
  ) {
    return { data: { success: true } };
  }

  if (name === "invoicePaymentWebhook" || name === "invoicePackWebhook") {
    return { data: { received: true } };
  }

  if (name === "confirmAndActivate" || name === "forceActivate") {
    return { data: { success: true } };
  }

  // No SMS is ever sent, and verifyPhoneCode returned success for ANY code --
  // the two lies propped each other up. Mitigated only because phone_verified
  // is enforced nowhere in src/, so the screen gates nothing today.
  if (name === "sendPhoneVerification" || name === "verifyPhoneCode") {
    return notImplemented(name);
  }

  if (name === "assignAppointment") {
    return { data: { success: true } };
  }

  if (name === "createInvoicePaymentLink") {
    return { data: { success: true, payment_link: "#" } };
  }

  // Shown to a client immediately after a real payment. The fake row rendered
  // a receipt reading INV-000, $0.00 at the exact moment money moved.
  if (name === "getInvoiceBySession") {
    return notImplemented(name);
  }

  // ---------------------------------------------------------------------
  // Catch-all for a name with NO handling at all.
  //
  // This used to `return { data: { success: true } }` -- it fabricated success
  // for every unimplemented function, not just the ones without a stub branch.
  // That is how quote approval shipped a green "Quote Approved!" for a quote
  // nobody approved, and how the public Contact form told people their message
  // had been sent while discarding it.
  //
  // Same contract as the explicit stubs above, so a caller handles "not built"
  // identically whether or not someone wrote a branch for it.
  //
  // The build-time guard is check-functions.cjs; this is the runtime backstop.
  // ---------------------------------------------------------------------
  return notImplemented(name);
}

/**
 * Ask the model for something, shaped.
 *
 * THIS USED TO BE A STUB. It ignored the prompt and returned the same two line
 * items -- Labor x4 @ $85, Materials x1 @ $240 -- to all six call sites, every
 * time, for every input. AI invoicing, AI quotes from a photo, voice dictation
 * and the receipt scanner were all that function. It is the product's stated
 * differentiator and it did not exist.
 *
 * Now a real edge function. The key lives in Supabase secrets and never reaches
 * this bundle: a key shipped in client JS is a public key.
 *
 * Throws rather than returning a fallback. Every caller must handle failure by
 * telling the contractor to write it manually -- there is no canned draft to
 * fall back to, deliberately, because a plausible wrong answer is worse than an
 * honest missing one.
 *
 * @throws {Error} with `.notConfigured` true when no provider key is set.
 */
async function invokeLLM({ prompt, response_json_schema, file_urls }) {
  const { data } = await handleFunctionInvoke("invokeLLM", {
    prompt,
    response_json_schema,
    file_urls,
  });

  if (!data || data.success === false) {
    const err = new Error(
      data?.error || "The AI request failed. Please write this manually.",
    );
    err.notConfigured = Boolean(data?.not_configured || data?.not_implemented);
    err.rateLimited = Boolean(data?.rate_limited);
    throw err;
  }

  // `success` is transport-level, not part of any caller's schema.
  const { success, ...result } = data;
  return result;
}

export const sdk = {
  auth: {
    me: async () => {
      const {
        data: { user },
        error,
      } = await supabase.auth.getUser();
      if (error || !user) return null;

      // Ensure fallback demo data exists for this user locally
      seedAllDataForUser(user.id);

      // Try to fetch extended profile from Supabase (ignore if table missing or row not found)
      let profile = null;
      try {
        const { data, error } = await supabase
          .from("profiles")
          .select("*")
          .eq("id", user.id)
          .maybeSingle();
        if (error && error.code !== "PGRST116") throw error;
        profile = data;
      } catch (profileError) {
        // Table doesn't exist yet or no profile row — that's okay, use auth metadata
      }

      return {
        id: user.id,
        email: user.email,
        full_name: profile?.full_name || user.user_metadata?.full_name || "",
        onboarding_completed: profile?.onboarding_completed || false,
        role: profile?.role || "admin",
        ...profile,
      };
    },
    logout: async () => {
      await supabase.auth.signOut();
      localStorage.removeItem("invoicium_user");
      window.location.href = "/";
    },
    redirectToLogin: (returnUrl) => {
      window.location.href = buildLoginUrl(returnUrl);
    },
    isAuthenticated: async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession();
      return Boolean(session);
    },
    signInWithGoogle: async (returnUrl) => {
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: "google",
        options: {
          redirectTo: buildLoginUrl(returnUrl),
          queryParams: {
            prompt: "select_account",
          },
        },
      });
      if (error) throw error;
      return data;
    },
    register: async ({ email, password, ...metadata }) => {
      const { data, error } = await supabase.auth.signUp({
        email,
        password,
        options: { data: metadata },
      });
      if (error) throw error;
      return data.user;
    },
    updateMe: async (updates) => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");
      const { error } = await supabase
        .from("profiles")
        .update(updates)
        .eq("id", user.id);
      if (error) throw error;
      return { ...user, ...updates };
    },
  },
  entities: {
    Client,
    Invoice,
    Quote,
    Job,
    JobPhoto,
    JobMaterial,
    JobNote,
    BusinessSettings,
    Subscription,
    RecurringInvoice,
    InvoiceTemplate,
    Receipt,
    EmployeeProfile,
    CrewInvite,
    CrewMemberSettings,
    TimeEntry,
    // Aliases for any legacy references
    Query: {
      list: () => Promise.resolve([]),
    },
    UserSpecialty: {
      filter: () =>
        Promise.resolve([{ user_id: null, primary_specialty: "general" }]),
      create: (p) => localDataEngine.create("UserSpecialty", p),
      update: (id, p) => localDataEngine.update("UserSpecialty", id, p),
    },
    JobExpense: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("JobExpense", p),
      update: (id, p) => localDataEngine.update("JobExpense", id, p),
    },
    Notification: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("Notification", p),
      update: (id, p) => localDataEngine.update("Notification", id, p),
      delete: (id) => localDataEngine.delete("Notification", id),
      subscribe: () => {
        return () => {};
      },
    },
    Review: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("Review", p),
    },
    ContractorListing: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("ContractorListing", p),
      update: (id, p) => localDataEngine.update("ContractorListing", id, p),
    },
    Appointment: {
      filter: () => Promise.resolve([]),
      create: (p) => localDataEngine.create("Appointment", p),
      update: (id, p) => localDataEngine.update("Appointment", id, p),
      delete: (id) => localDataEngine.delete("Appointment", id),
    },
    ServicePreset: {
      filter: () =>
        Promise.resolve([
          {
            id: "sp_1",
            name: "Handyman Service",
            is_system: true,
            items: [{ description: "General labor", quantity: 1, rate: 75 }],
          },
          {
            id: "sp_2",
            name: "Painting",
            is_system: true,
            items: [
              { description: "Interior painting", quantity: 1, rate: 450 },
            ],
          },
          {
            id: "sp_3",
            name: "Plumbing Repair",
            is_system: true,
            items: [{ description: "Plumbing fix", quantity: 1, rate: 120 }],
          },
        ]),
      create: (p) => localDataEngine.create("ServicePreset", p),
      update: (id, p) => localDataEngine.update("ServicePreset", id, p),
    },
    CustomServiceTemplate: {
      filter: (filters, sort, limit) =>
        localDataEngine.list("CustomServiceTemplate", filters, sort, limit),
      list: (filters, sort, limit) =>
        localDataEngine.list("CustomServiceTemplate", filters, sort, limit),
      create: (p) => localDataEngine.create("CustomServiceTemplate", p),
      update: (id, p) => localDataEngine.update("CustomServiceTemplate", id, p),
      delete: (id) => localDataEngine.delete("CustomServiceTemplate", id),
    },
    TaskNote: {
      filter: (filters, sort, limit) =>
        localDataEngine.list("TaskNote", filters, sort, limit),
      create: (p) => localDataEngine.create("TaskNote", p),
      update: (id, p) => localDataEngine.update("TaskNote", id, p),
      delete: (id) => localDataEngine.delete("TaskNote", id),
    },
    JobPhotoShare: {
      filter: (filters, sort, limit) =>
        localDataEngine.list("JobPhotoShare", filters, sort, limit),
      create: (p) => localDataEngine.create("JobPhotoShare", p),
      update: (id, p) => localDataEngine.update("JobPhotoShare", id, p),
      delete: (id) => localDataEngine.delete("JobPhotoShare", id),
    },
  },
  functions: {
    invoke: handleFunctionInvoke,
  },
  appLogs: {
    logUserInApp: () => Promise.resolve(),
  },
  integrations: {
    Core: {
      InvokeLLM: invokeLLM,
      SendEmail: () => Promise.resolve({ success: true }),
      SendSMS: () => Promise.resolve({ success: true }),
      UploadFile: uploadFile,
      GenerateImage: () =>
        Promise.resolve({
          url: "https://placehold.co/600x400?text=Generated+Image",
        }),
      ExtractDataFromUploadedFile: () => Promise.resolve({ data: {} }),
    },
  },
};

export default sdk;
