"""Exercise get-public-quote / approve-quote as an ANONYMOUS caller.

The important assertion here is the branding one. PublicQuote used to read
BusinessSettings.list() and take [0] -- the first row in the table, not the
row belonging to the quote's owner. Under the old RLS that returned empty, so
the bug was dormant; behind a service role it would have returned SOMEONE
ELSE'S business name, logo, address and phone.

One settings row cannot tell "resolved by user_id" apart from "took [0]", so
this creates a SECOND settings row, owned by a different user, with a
distinctive name -- and asserts the payload carries that name rather than the
pre-existing one. Everything it creates, it deletes.

Usage: python scripts/test-public-quote.py
"""
import json
import sys
import urllib.request
import urllib.error

from _env import require
from q import run_sql

SUPABASE_URL = require('VITE_SUPABASE_URL').rstrip('/')
ANON = require('VITE_SUPABASE_ANON_KEY')

MARKER = 'ZZ-TEST-OWNER-A'


def call(fn, body):
    req = urllib.request.Request(
        f'{SUPABASE_URL}/functions/v1/{fn}',
        data=json.dumps(body).encode('utf-8'),
        headers={
            'Authorization': f'Bearer {ANON}',
            'apikey': ANON,
            'Content-Type': 'application/json',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
                          'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36',
        },
        method='POST',
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.status, json.loads(resp.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        raw = e.read().decode('utf-8')
        try:
            return e.code, json.loads(raw)
        except ValueError:
            return e.code, raw


def sql(query):
    status, body = run_sql(query)
    if status >= 300:
        sys.exit(f'SQL failed: {status}\n{body}\nquery: {query[:200]}')
    return json.loads(body)


results = []


def check(label, cond, detail=''):
    results.append(bool(cond))
    print(f'  {"PASS" if cond else "FAIL"}  {label}'
          f'{(" -- " + detail) if detail and not cond else ""}')
    return cond


def main():
    # User A has no BusinessSettings row of their own; the only existing row
    # belongs to user B. That is what makes the discriminator work.
    users = sql('select id, email from auth.users order by created_at')
    owner = users[0]['id']
    existing = sql('select user_id, business_name from public."BusinessSettings"')
    other_names = [r['business_name'] for r in existing if r['user_id'] != owner]
    if not other_names:
        sys.exit('Need at least one BusinessSettings row owned by a DIFFERENT user '
                 'for the branding assertion to mean anything.')
    print(f'Owner under test: {users[0]["email"]}')
    print(f'Decoy business already in the table: {other_names[0]!r}\n')

    quote_id = None
    made_settings = False
    try:
        # --- Fixtures -----------------------------------------------------
        sql(f"""insert into public."BusinessSettings" (user_id, business_name, phone, currency)
                values ('{owner}', '{MARKER}', '+15550000001', 'CAD')""")
        made_settings = True

        rows = sql(f"""insert into public."Quote"
                         (user_id, quote_number, client_name, client_email, items,
                          subtotal, tax_rate, tax_amount, total, status,
                          date_issued, expiry_date, notes)
                       values
                         ('{owner}', 'ZZ-TEST-001', 'Test Client', 'client@example.com',
                          '[{{"description":"Test line","quantity":2,"rate":50,"amount":100,"secret":"leak"}}]'::jsonb,
                          100, 13, 13, 113, 'sent',
                          now(), now() + interval '30 days', 'Test notes')
                       returning id, public_id, approval_token""")
        quote = rows[0]
        quote_id = quote['id']
        public_id = quote['public_id']

        # --- The migration must have supplied both credentials ------------
        print('credentials generated by the database:')
        check('public_id auto-generated', bool(public_id), str(quote))
        check('approval_token auto-generated', bool(quote['approval_token']), str(quote))

        # --- Happy path ---------------------------------------------------
        print('\nget-public-quote, valid public_id:')
        status, body = call('get-public-quote', {'public_id': public_id})
        check('200', status == 200, f'{status} {body}')
        check('success', body.get('success') is True, str(body))
        q = body.get('quote', {})
        check('quote number matches', q.get('number') == 'ZZ-TEST-001')
        check('total matches', float(q.get('total', -1)) == 113.0)

        # --- THE BRANDING TRAP -------------------------------------------
        print('\nbranding resolves to the OWNING business (the [0] trap):')
        biz = body.get('business', {})
        check(f'business name is the owner\'s ({MARKER})',
              biz.get('name') == MARKER, f'got {biz.get("name")!r}')
        for decoy in other_names:
            check(f'payload does NOT contain the decoy {decoy!r}',
                  decoy not in json.dumps(body))

        # --- Narrowed payload --------------------------------------------
        print('\nnarrowed payload:')
        flat = json.dumps(body)
        check('no quote id', quote_id not in flat)
        check('no approval_token', quote['approval_token'] not in flat)
        check('no user_id', owner not in flat)
        check('no client_email', 'client@example.com' not in flat)
        check('jsonb extras dropped from items', 'leak' not in flat)
        check('top level is exactly the four sections',
              set(body.keys()) == {'success', 'quote', 'client', 'business', 'capabilities'},
              str(sorted(body.keys())))
        check('client is name only', set(body.get('client', {}).keys()) == {'name'})
        check('item keys are the enumerated four',
              set(q['items'][0].keys()) == {'description', 'quantity', 'rate', 'amount'},
              str(sorted(q['items'][0].keys())))

        # --- Rejections ---------------------------------------------------
        print('\nrejections:')
        status, body2 = call('get-public-quote', {'public_id': 'no'})
        check('too-short id -> 404', status == 404, f'{status} {body2}')
        status, body2 = call('get-public-quote', {'public_id': '11111111-2222-4333-8444-555555555555'})
        check('unknown id -> 404', status == 404, f'{status} {body2}')
        check('unknown id leaks nothing', 'quote' not in body2)

        # --- Revocation ---------------------------------------------------
        print('\nrevocation:')
        sql(f"""update public."Quote" set public_link_revoked_at = now() where id = '{quote_id}'""")
        status, body2 = call('get-public-quote', {'public_id': public_id})
        check('revoked -> 410', status == 410 and body2.get('reason') == 'revoked', f'{status} {body2}')
        check('revoked returns NO payload', 'quote' not in body2 and 'business' not in body2)
        status, body2 = call('approve-quote', {'public_id': public_id})
        check('approve on a revoked link is refused', not body2.get('success'), str(body2))
        after = sql(f"""select status from public."Quote" where id = '{quote_id}'""")[0]
        check('revoked approve did NOT change status', after['status'] == 'sent', str(after))
        sql(f"""update public."Quote" set public_link_revoked_at = null where id = '{quote_id}'""")

        # --- View recording ------------------------------------------------
        print('\nview recording:')
        sql(f"""update public."Quote" set last_viewed_at = null, updated_at = now() - interval '10 minutes'
                 where id = '{quote_id}'""")
        before = sql(f"""select view_count from public."Quote" where id = '{quote_id}'""")[0]
        status, body2 = call('get-public-quote', {'public_id': public_id, 'action': 'record_view'})
        aft = sql(f"""select view_count, first_viewed_at from public."Quote" where id = '{quote_id}'""")[0]
        check('view_count advanced', aft['view_count'] > before['view_count'],
              f'{before["view_count"]} -> {aft["view_count"]} (outcome={body2.get("outcome")})')
        check('first_viewed_at set', aft['first_viewed_at'] is not None)
        status, body2 = call('get-public-quote',
                             {'public_id': public_id, 'action': 'record_view', 'preview': True})
        check('preview does not count', body2.get('outcome') == 'skipped_preview', str(body2))
        hits = sql(f"""select count(*) as n from public."PublicLinkHit" where quote_id = '{quote_id}'""")[0]['n']
        check('hits logged against the quote', int(hits) > 0, f'{hits} rows')

        # --- Approval via the page's credential ---------------------------
        print('\napproval (button wired to approve-quote, via public_id):')
        status, body2 = call('approve-quote', {'public_id': public_id})
        check('approve succeeds', body2.get('success') is True, f'{status} {body2}')
        approved = sql(f"""select status from public."Quote" where id = '{quote_id}'""")[0]
        check('status is now approved in the DATABASE', approved['status'] == 'approved', str(approved))
        status, body2 = call('approve-quote', {'public_id': public_id})
        check('second approve reports already_approved',
              body2.get('already_approved') is True, str(body2))
        status, body2 = call('get-public-quote', {'public_id': public_id})
        check('page now says can_approve false',
              body2.get('capabilities', {}).get('can_approve') is False,
              str(body2.get('capabilities')))

    finally:
        print('\ncleanup:')
        if quote_id:
            sql(f"""delete from public."PublicLinkHit" where quote_id = '{quote_id}'""")
            sql(f"""delete from public."Quote" where id = '{quote_id}'""")
            print('  removed test quote and its hits')
        if made_settings:
            sql(f"""delete from public."BusinessSettings" where business_name = '{MARKER}'""")
            print('  removed test settings row')
        sql("""delete from public."PublicLinkHit" where invoice_id is null and quote_id is null""")
        left = sql("""select count(*) as n from public."Quote" """)[0]['n']
        print(f'  quotes remaining in table: {left}')

    ok = all(results)
    print('\n' + ('ALL PASS' if ok else 'FAILURES ABOVE'))
    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
