import { useEffect, useRef } from "react";
import { VERT, getPreset, DEFAULT_PRESET_ID } from "@/components/ui/shader-presets";

/**
 * ShaderBackground — the WebGL runtime for the animated backgrounds.
 *
 * The programs themselves live in shader-presets.js, generated by the 21st.dev
 * Shader Builder; this file is only the plumbing they all share -- context
 * setup, a fullscreen triangle, the uniform uploads, and the rules about when
 * it is allowed to draw. Pass `preset` to choose one.
 *
 * Zero dependencies: one WebGL canvas that fills its parent. Drop it behind
 * content with:
 *   <div className="relative">
 *     <ShaderBackground className="absolute inset-0" />
 *     …
 *
 * Adapted from the upstream TSX for this codebase:
 *  - JSX with JSDoc instead of TS types. components.json sets "tsx": false and
 *    eslint.config.js matches only {js,mjs,cjs,jsx}, so a .tsx file would ship
 *    unlinted.
 *  - No "use client" -- this is a Vite SPA, not the Next.js App Router.
 *  - Honours prefers-reduced-motion BY DEFAULT, drawing a single frozen frame
 *    instead of animating: a perpetually moving full-viewport background is
 *    close to the canonical case that guideline exists for. Callers can opt
 *    out with respectReducedMotion={false}, which is correct only where the
 *    user themselves switched the animation on.
 */

/** @type {WeakMap<HTMLCanvasElement, number>} */
const pendingContextReleases = new WeakMap();

/**
 * @param {{ className?: string, respectReducedMotion?: boolean,
 *   preset?: string }} props
 *   preset is a key of SHADER_PRESETS; an unknown one falls back to the
 *   default rather than rendering nothing, so a stored id that is later
 *   removed degrades to a background instead of a blank page.
 *
 *   respectReducedMotion defaults to true, which is right for a decorative
 *   background nobody asked for. Pass false where the user has explicitly
 *   switched the animation on: a setting called "Animated background" that a
 *   person deliberately enabled IS the consent, and an OS-wide default should
 *   not silently overrule the specific choice they just made.
 */
export function ShaderBackground({
  className,
  respectReducedMotion = true,
  preset: presetId = DEFAULT_PRESET_ID,
}) {
  const canvasRef = useRef(null);

  useEffect(() => {
    // Resolved inside the effect, and presetId is a dependency: switching
    // preset has to build a new program, so the whole context is torn down
    // and set up again rather than swapping uniforms on the live one.
    const { frag, uniforms } = getPreset(presetId);
    const canvas = canvasRef.current;
    if (!canvas) return undefined;
    const pendingRelease = pendingContextReleases.get(canvas);
    if (pendingRelease !== undefined) window.clearTimeout(pendingRelease);
    pendingContextReleases.delete(canvas);
    // A full-viewport surface repainting every frame forever is the case the
    // guideline is about. Under reduced motion it draws once and stops.
    const prefersReducedMotion =
      respectReducedMotion &&
      typeof window.matchMedia === "function" &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    // preserveDrawingBuffer is not optional here, on either path.
    //
    // WebGL throws the drawing buffer away after each composite unless told
    // not to, so what is on screen depends on whether a fresh frame landed
    // before the compositor looked. Measured both ways: with it off, the
    // draw-once path (anyone with reduced motion enabled) renders nothing at
    // all, and even the animating path captured blank. With it on, both paths
    // produce the full palette.
    //
    // The cost is one buffer copy per frame on a surface already capped at 2
    // megapixels and sitting at 30% opacity behind the page -- far cheaper
    // than a background that is invisible on some machines and not others.
    const gl = canvas.getContext("webgl", {
      antialias: false,
      preserveDrawingBuffer: true,
    });
    if (!gl) return undefined;

    // Upstream checks neither COMPILE_STATUS nor LINK_STATUS. A GLSL error
    // there fails completely silently -- you get a canvas that draws nothing
    // and no clue why, on whichever driver happens to reject the source. This
    // reports it and bails, so the page falls back to its flat background
    // instead of showing an invisible dead canvas.
    const compile = (type, src, label) => {
      const s = gl.createShader(type);
      gl.shaderSource(s, src);
      gl.compileShader(s);
      if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) {
        console.error(
          `ShaderBackground: ${label} shader failed to compile\n` +
            gl.getShaderInfoLog(s),
        );
        gl.deleteShader(s);
        return null;
      }
      return s;
    };
    const program = gl.createProgram();
    const vertexShader = compile(gl.VERTEX_SHADER, VERT, "vertex");
    const fragmentShader = compile(gl.FRAGMENT_SHADER, frag, "fragment");
    if (!vertexShader || !fragmentShader) {
      if (vertexShader) gl.deleteShader(vertexShader);
      if (fragmentShader) gl.deleteShader(fragmentShader);
      gl.deleteProgram(program);
      return undefined;
    }
    gl.attachShader(program, vertexShader);
    gl.attachShader(program, fragmentShader);
    gl.linkProgram(program);
    gl.deleteShader(vertexShader);
    gl.deleteShader(fragmentShader);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      console.error(
        "ShaderBackground: program failed to link\n" +
          gl.getProgramInfoLog(program),
      );
      gl.deleteProgram(program);
      return undefined;
    }
    gl.useProgram(program);

    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 3, -1, -1, 3]),
      gl.STATIC_DRAW,
    );
    const loc = gl.getAttribLocation(program, "a_position");
    gl.enableVertexAttribArray(loc);
    gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);

    const uni = {
      colors: gl.getUniformLocation(program, "u_colors"),
      scene: gl.getUniformLocation(program, "u_scene"),
      shape: gl.getUniformLocation(program, "u_shape"),
      surface: gl.getUniformLocation(program, "u_surface"),
      finish: gl.getUniformLocation(program, "u_finish"),
      transform: gl.getUniformLocation(program, "u_transform"),
      space: gl.getUniformLocation(program, "u_space"),
      cursor: gl.getUniformLocation(program, "u_cursor"),
    };
    gl.uniform3fv(uni.colors, new Float32Array(uniforms.colors.flat()));
    gl.uniform4f(
      uni.shape,
      uniforms.scale,
      uniforms.intensity,
      uniforms.paramA,
      uniforms.warp,
    );
    gl.uniform4f(
      uni.surface,
      uniforms.detail,
      uniforms.contrast,
      uniforms.brightness,
      uniforms.saturation,
    );
    gl.uniform4f(
      uni.finish,
      uniforms.hue,
      uniforms.vignette,
      uniforms.blur,
      uniforms.grain,
    );
    gl.uniform4f(
      uni.transform,
      uniforms.seed,
      uniforms.rotate,
      uniforms.drift,
      uniforms.oklab,
    );
    gl.uniform4f(
      uni.cursor,
      0,
      uniforms.cursorEffect,
      uniforms.cursorStrength,
      uniforms.cursorRadius,
    );

    let targetX = 0;
    let targetY = 0;
    let targetPresence = 0;
    let mouseX = 0;
    let mouseY = 0;
    let cursorPresence = 0;
    let pointerKnown = false;
    let pointerClientX = 0;
    let pointerClientY = 0;
    let bounds = canvas.getBoundingClientRect();
    let raf = 0;
    let lastNow = null;
    let visible = document.visibilityState === "visible";
    let inView = true;
    let disposed = false;
    const start = performance.now();
    const timeAnimated =
      !prefersReducedMotion && Math.abs(uniforms.timeScale) > 0.0001;

    const resizeCanvas = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      const rawWidth = Math.max(1, Math.round(bounds.width * dpr));
      const rawHeight = Math.max(1, Math.round(bounds.height * dpr));
      const pixelScale = Math.min(
        1,
        Math.sqrt(2_000_000 / Math.max(1, rawWidth * rawHeight)),
      );
      const width = Math.max(1, Math.round(rawWidth * pixelScale));
      const height = Math.max(1, Math.round(rawHeight * pixelScale));
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width;
        canvas.height = height;
        gl.viewport(0, 0, width, height);
      }
    };

    function requestRender() {
      if (!disposed && visible && inView && raf === 0) {
        raf = requestAnimationFrame(render);
      }
    }

    const updatePointerTarget = () => {
      if (!pointerKnown) return;
      if (bounds.width === 0 || bounds.height === 0) return;
      const inside =
        pointerClientX >= bounds.left &&
        pointerClientX <= bounds.right &&
        pointerClientY >= bounds.top &&
        pointerClientY <= bounds.bottom;
      if (!inside) {
        targetPresence = 0;
        requestRender();
        return;
      }
      const nextX = ((pointerClientX - bounds.left) / bounds.width) * 2 - 1;
      const nextY = -(((pointerClientY - bounds.top) / bounds.height) * 2 - 1);
      if (targetPresence === 0 && cursorPresence < 0.01) {
        mouseX = nextX;
        mouseY = nextY;
      }
      targetX = nextX;
      targetY = nextY;
      targetPresence = 1;
      requestRender();
    };
    const onPointerMove = (event) => {
      pointerKnown = true;
      pointerClientX = event.clientX;
      pointerClientY = event.clientY;
      bounds = canvas.getBoundingClientRect();
      updatePointerTarget();
    };
    const onPointerLeave = () => {
      pointerKnown = false;
      targetPresence = 0;
      requestRender();
    };
    const updateLayout = () => {
      bounds = canvas.getBoundingClientRect();
      resizeCanvas();
      updatePointerTarget();
      requestRender();
    };
    window.addEventListener("resize", updateLayout);
    if (uniforms.cursorEnabled) {
      window.addEventListener("pointermove", onPointerMove, { passive: true });
      window.addEventListener("pointercancel", onPointerLeave);
      window.addEventListener("scroll", updateLayout, true);
      window.addEventListener("blur", onPointerLeave);
      document.documentElement.addEventListener("pointerleave", onPointerLeave);
    }

    const resizeObserver = new ResizeObserver(updateLayout);
    resizeObserver.observe(canvas);
    const intersectionObserver = new IntersectionObserver(([entry]) => {
      inView = entry?.isIntersecting ?? true;
      if (inView) requestRender();
      else if (raf !== 0) {
        cancelAnimationFrame(raf);
        raf = 0;
        lastNow = null;
      }
    });
    intersectionObserver.observe(canvas);
    const onVisibilityChange = () => {
      visible = document.visibilityState === "visible";
      if (visible) requestRender();
      else if (raf !== 0) {
        cancelAnimationFrame(raf);
        raf = 0;
        lastNow = null;
      }
    };
    document.addEventListener("visibilitychange", onVisibilityChange);

    function render(now) {
      raf = 0;
      if (disposed || !visible || !inView) return;
      const dt = lastNow === null ? 0 : Math.min((now - lastNow) / 1000, 0.1);
      lastNow = now;
      const follow = 1 - Math.exp(-12 * dt);
      mouseX += (targetX - mouseX) * follow;
      mouseY += (targetY - mouseY) * follow;
      cursorPresence += (targetPresence - cursorPresence) * follow;
      resizeCanvas();
      const width = canvas.width;
      const height = canvas.height;
      gl.uniform4f(
        uni.scene,
        width,
        height,
        // Frozen at t=0 under reduced motion, so the one frame drawn is stable.
        prefersReducedMotion
          ? 0
          : ((now - start) / 1000) * uniforms.timeScale,
        uniforms.colorCount,
      );
      gl.uniform4f(uni.space, uniforms.offsetX, uniforms.offsetY, mouseX, mouseY);
      gl.uniform4f(
        uni.cursor,
        uniforms.cursorEnabled ? cursorPresence : 0,
        uniforms.cursorEffect,
        uniforms.cursorStrength,
        uniforms.cursorRadius,
      );
      gl.drawArrays(gl.TRIANGLES, 0, 3);
      const pointerSettling =
        Math.abs(targetX - mouseX) > 0.001 ||
        Math.abs(targetY - mouseY) > 0.001 ||
        Math.abs(targetPresence - cursorPresence) > 0.001;
      if (timeAnimated || pointerSettling) requestRender();
      else lastNow = null;
    }
    requestRender();
    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      resizeObserver.disconnect();
      intersectionObserver.disconnect();
      document.removeEventListener("visibilitychange", onVisibilityChange);
      window.removeEventListener("resize", updateLayout);
      if (uniforms.cursorEnabled) {
        window.removeEventListener("pointermove", onPointerMove);
        window.removeEventListener("pointercancel", onPointerLeave);
        window.removeEventListener("scroll", updateLayout, true);
        window.removeEventListener("blur", onPointerLeave);
        document.documentElement.removeEventListener(
          "pointerleave",
          onPointerLeave,
        );
      }
      gl.deleteBuffer(buf);
      gl.deleteProgram(program);
      const releaseTimer = window.setTimeout(() => {
        if (pendingContextReleases.get(canvas) !== releaseTimer) return;
        pendingContextReleases.delete(canvas);
        gl.getExtension("WEBGL_lose_context")?.loseContext();
        canvas.width = 1;
        canvas.height = 1;
      }, 0);
      pendingContextReleases.set(canvas, releaseTimer);
    };
  }, [presetId, respectReducedMotion]);

  return (
    <canvas
      ref={canvasRef}
      className={className}
      style={{ display: "block", width: "100%", height: "100%" }}
    />
  );
}

export default ShaderBackground;
